/*Problem : Given a smart phone Keypad , input is a number and you  have to print all possible names(string) generated by keypad using the given no. */

#include <bits/stdc++.h>
using namespace std;
char keypad[][5]={"","","ABC","DEF","GHI","JKL","MNO","PQRS","TUV","WXYZ"};
void printphonekeypad(char *in,char *out, int i, int j)
{
    if(in[i]=='\0')
    {
        out[j]='\0';
        cout<<out<<",";
        return;
    }
    int digit=in[i]-'0';
    if(digit==0 || digit==1)
    {
        printphonekeypad(in,out,i+1,j);
    }
    for(int k=0;keypad[digit][k]!=0;k++)
    {
        out[j]=keypad[digit][k];
        printphonekeypad(in,out,i+1,j+1);
    }
}
int main()
{
    char in[100];
    char out[100];
    cin>>in;
    printphonekeypad(in,out,0,0);
}
